on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: build
        run: cargo build --release
      
      - name: Archive using tar
        uses: juankaram/archive-action@v1
        with: |
          tar -czvf publis.tar.gz target/release/publis

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publis.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

